- name: Configure LLDP on Core Switches
  cisco.nxos.nxos_feature:
    feature: lldp
    state: enabled
  when: (role == "Core") and (ansible_network_os == 'cisco.nxos.nxos')
  tags: [ lldp, features ]

- name: Configure VPC on Core Switches
  cisco.nxos.nxos_feature:
    feature: vpc
    state: enabled
  when: (role == "Core") and (ansible_network_os == 'cisco.nxos.nxos')
  tags: [ vpc, features ]

- name: Configure Interface VLAN on Core
  cisco.nxos.nxos_feature:
    feature: interface-vlan
    state: enabled
  when: (role == "Core") and (ansible_network_os == 'cisco.nxos.nxos')
  tags: [ interface-vlan, features ]
    
- name: Configure OSPF on Core
  cisco.nxos.nxos_feature:
    feature: ospf 
    state: enabled
  when: (role == "Core") and (ansible_network_os == 'cisco.nxos.nxos')
  tags: [ ospf, features ]