# Create the VLAN
- name: Create VLANs
  nxos_vlans:
    config:
    - vlan_id: 10
      name: linuxVLAN10
      enabled: yes
      state: active
    state: merged

# Configure Interface VLAN with an IP, which also creates the interface VLAN entries
- name: Assign IP to VLAN 10 (Core1)
  nxos_l3_interfaces:
    config:
    - name: vlan10
      ipv4:
      - address: 192.168.60.1/25
    state: merged
  when: (switchName == "nxosCore1") and (ansible_network_os == 'cisco.nxos.nxos')

#At this point the interface VLAN is disabled and we want it enabled so it 

- name: Enable interface VLAN 10 and 11 on Core switches
  nxos_interfaces:
    config:
      - name: Vlan10
        enabled: True
  when: (role == "Core") and (ansible_network_os == 'cisco.nxos.nxos')

  # But basically nothing happens.